/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package panaderia;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.HashSet;
import java.util.Set;
import javax.swing.JOptionPane;
import javax.swing.SpinnerNumberModel;
import javax.swing.Timer;
import static panaderia.Order.Controller;

/**
 *
 * @author eliasvidal
 */
public class vista extends javax.swing.JFrame {

    /**
     * Creates new form vista
     */
    public vista() {
        initComponents();
        text.setVisible(false);
        SpinnerNumberModel model1 = new SpinnerNumberModel(0, 0, 100, 1);
        SpinnerNumberModel model2 = new SpinnerNumberModel(0, 0, 100, 1);
        SpinnerNumberModel model3 = new SpinnerNumberModel(0, 0, 100, 1);
        
        amountS.setModel(model1);
        amountB.setModel(model2);
        amountD.setModel(model3);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        id = new javax.swing.JTextField();
        addS = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        comboBoxSoda = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        comboBoxBread = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        comboBoxDessert = new javax.swing.JComboBox<>();
        addB = new javax.swing.JButton();
        addD = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        generate = new javax.swing.JButton();
        comboBoxType = new javax.swing.JComboBox<>();
        bag = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        amountS = new javax.swing.JSpinner();
        amountB = new javax.swing.JSpinner();
        amountD = new javax.swing.JSpinner();
        text = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(397, 49, 119, -1));

        addS.setText("Add");
        addS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSActionPerformed(evt);
            }
        });
        jPanel1.add(addS, new org.netbeans.lib.awtextra.AbsoluteConstraints(248, 40, -1, -1));

        jLabel1.setText("ID");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(373, 52, -1, -1));

        jLabel2.setText("Soda");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 43, -1, -1));

        comboBoxSoda.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Personal", "Pet", "Familiar" }));
        jPanel1.add(comboBoxSoda, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 40, 119, -1));

        jLabel3.setText("Bread");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 93, -1, -1));

        comboBoxBread.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));
        jPanel1.add(comboBoxBread, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 90, 119, -1));

        jLabel4.setText("Dessert");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 142, -1, -1));

        comboBoxDessert.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chocolate", "Vanilla", "Custom Flavor" }));
        jPanel1.add(comboBoxDessert, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 139, -1, -1));

        addB.setText("Add");
        addB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBActionPerformed(evt);
            }
        });
        jPanel1.add(addB, new org.netbeans.lib.awtextra.AbsoluteConstraints(248, 90, -1, -1));

        addD.setText("Add");
        addD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDActionPerformed(evt);
            }
        });
        jPanel1.add(addD, new org.netbeans.lib.awtextra.AbsoluteConstraints(248, 139, -1, -1));

        jLabel5.setText("Name");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(351, 93, -1, -1));
        jPanel1.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(397, 90, 119, -1));

        jLabel6.setText("Type");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(356, 134, -1, -1));

        generate.setText("Generate receipt");
        generate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateActionPerformed(evt);
            }
        });
        jPanel1.add(generate, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 195, -1, -1));

        comboBoxType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "C" }));
        jPanel1.add(comboBoxType, new org.netbeans.lib.awtextra.AbsoluteConstraints(397, 131, -1, -1));

        bag.setText("Bag");
        jPanel1.add(bag, new org.netbeans.lib.awtextra.AbsoluteConstraints(534, 91, -1, -1));

        jLabel7.setText("Amount");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 20, 50, -1));
        jPanel1.add(amountS, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, 50, -1));
        jPanel1.add(amountB, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 50, -1));
        jPanel1.add(amountD, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 50, -1));

        text.setText("jLabel8");
        jPanel1.add(text, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 629, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void generateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateActionPerformed
        // TODO add your handling code here:
        Controller.client(name.getText(), Integer.parseInt(id.getText()), String.valueOf(comboBoxType.getSelectedItem()));
        Controller.setPlasticBag(bag.isSelected());

        String sodaReceipt = "";
        for (int i = 0; i < Controller.sodaSize(); i++) {
            sodaReceipt = sodaReceipt + "<tr><td>Soda</td><td align='right'>Size: " + Controller.getSoda(i).getSize() + "</td>"
            + "<td align='right'>" + Controller.getSoda(i).getAmount() + "</td>"
            + "<td align='right'>" + Controller.getSoda(i).CalcPrice()+ "</td></tr>";
        }

        String breadReceipt = "";
        for (int i = 0; i < Controller.breadSize(); i++) {
            breadReceipt = breadReceipt + "<tr><td>Bread</td><td align='right'>Type: " + Controller.getBread(i).getType() + "</td>"
            + "<td align='right'>" + Controller.getBread(i).getAmount() + "</td>"
            + "<td align='right'>" + Controller.getBread(i).CalcPrice()+ "</td></tr>";
        }

        String dessertReceipt = "";
        for (int i = 0; i < Controller.dessertSize(); i++) {
            dessertReceipt = dessertReceipt + "<tr><td>Dessert</td><td align='right'>Flavor: " + Controller.getDessert(i).getFlavor() + "</td>"
            + "<td align='right'>" + Controller.getDessert(i).getAmount() + "</td>"
            + "<td align='right'>" + Controller.getDessert(i).CalcPrice()+ "</td></tr>";
        }

        String newText = "<html><body style='font-family: monospace;'>"
        + "<h2>----- Receipt -----</h2>"
        + "<table width='100%'>"
        + "<tr><td><b>Product</b></td><td align='right'><b>Description</b></td><td align='right'><b>Amount</b></td><td align='right'><b>Price</b></td></tr>"
        + sodaReceipt
        + breadReceipt
        + dessertReceipt
        + "</table>"
        + "<hr>"
        + "<table width='100%'>"
        + "<tr><td>Subtotal: </td><td align='right'>" + Controller.SubTotal() + "</td></tr>"
        + "<tr><td>Iva: </td><td align='right'>" + Controller.Iva()+ "</td></tr>"
        + "<tr><td>Client Discount: </td><td align='right'>" + Controller.calculateDiscountOnClient()+ "</td></tr>"
        + "<tr><td>Bag: </td><td align='right'>" + Controller.calculateBag()+ "</td></tr>"
        + "<tr><td>Total: </td><td align='right'>" + Controller.Total() + "</td></tr>"
        + "</table>"
        + "<hr>"
        + "<table width='100%'>"
        + "<tr><td>Name: </td><td align='right'>" + Controller.getClient().getName() + "</td></tr>"
        + "<tr><td>CC: </td><td align='right'>" + Controller.getClient().getId() + "</td></tr>"
        + "<tr><td>Client type: </td><td align='right'>" + Controller.getClient().getType() + "</td></tr>"
        + "</table>"
        + "<hr>"
        + "<p>Thank you for your purchase, " + Controller.getClient().getName() + "!";

        JOptionPane.showMessageDialog(null, newText);

    }//GEN-LAST:event_generateActionPerformed

    private void addDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDActionPerformed
        // TODO add your handling code here:
        String flavorD = comboBoxDessert.getSelectedItem().toString();
        int quantity = Integer.parseInt(amountD.getValue().toString());
        Controller.addDessert(flavorD, quantity);
        amountD.setValue(0);
        
        text.setText("Dessert was added");
        text.setVisible(true);
                
        // Set a timer to hide the label after 2 seconds (2000 milliseconds)
        Timer timer = new Timer(2000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                // Hide the label after 2 seconds
                text.setVisible(false);
            }
        });

        // Ensure the timer only runs once
        timer.setRepeats(false);
        // Start the timer
        timer.start();
        
    }//GEN-LAST:event_addDActionPerformed

    private void addBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBActionPerformed
        // TODO add your handling code here:
        int typeB = Integer.parseInt(comboBoxBread.getSelectedItem().toString());
        int quantity = Integer.parseInt(amountB.getValue().toString());
        Controller.addBread(typeB, quantity);
        amountB.setValue(0);
        
        text.setText("Bread was added");
        text.setVisible(true);
                
        // Set a timer to hide the label after 2 seconds (2000 milliseconds)
        Timer timer = new Timer(2000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                // Hide the label after 2 seconds
                text.setVisible(false);
            }
        });

        // Ensure the timer only runs once
        timer.setRepeats(false);
        // Start the timer
        timer.start();
    }//GEN-LAST:event_addBActionPerformed

    private void addSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSActionPerformed
        // TODO add your handling code here:
        String sizeS = comboBoxSoda.getSelectedItem().toString();
        int quantity = Integer.parseInt(amountS.getValue().toString());
        Controller.addSoda(sizeS, quantity);
        amountS.setValue(0);

        text.setText("Soda was added");
        text.setVisible(true);
                
        // Set a timer to hide the label after 2 seconds (2000 milliseconds)
        Timer timer = new Timer(2000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                // Hide the label after 2 seconds
                text.setVisible(false);
            }
        });

        // Ensure the timer only runs once
        timer.setRepeats(false);
        // Start the timer
        timer.start();
    }//GEN-LAST:event_addSActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addB;
    private javax.swing.JButton addD;
    private javax.swing.JButton addS;
    private javax.swing.JSpinner amountB;
    private javax.swing.JSpinner amountD;
    private javax.swing.JSpinner amountS;
    private javax.swing.JCheckBox bag;
    private javax.swing.JComboBox<String> comboBoxBread;
    private javax.swing.JComboBox<String> comboBoxDessert;
    private javax.swing.JComboBox<String> comboBoxSoda;
    private javax.swing.JComboBox<String> comboBoxType;
    private javax.swing.JButton generate;
    private javax.swing.JTextField id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField name;
    private javax.swing.JLabel text;
    // End of variables declaration//GEN-END:variables
}
